twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
    globals:
        app_title: Easyamap
        mail_support: anthony@easyamap.fr
        version: 1.4.0
        portail: https://www.easyamap.fr

when@test:
    twig:
        strict_variables: true
